### ISSUE TITLE
Can't login with existing Zhylon ID

### ISSUE THREAD

**Issue by TobyMaxham** [Zhylon/features#19]
After the Update to Sitealarm, I'm not able to Login with an existing ZhylonID.

What happend?

**Comment by NorbertFox** [comment]
Hey @TobyMaxham,

i fixed this in a new version.

The Problem: In the new ZhylonID-API we do not longer get the ID of a user as a numeric value.
All ID's are now hashed so we need to handle this when processing the oAuth Request.

Please review my PR.
Thanks!

**Comment by TobyMaxham** [comment]
Thanks for your quick response.
Your PR is almost correct.

If done a small change to it
```php
if (! empty($user->zhylon_id)) {
    return redirect('/login')->withErrors(
        __('auth.oauth.we are unable to login you in because you already have an account with this email')
    );
}
```

I think the problem was not the existing ones. The problem was the "hard" Exception that was thrown when an user with the same mail exists.
I have reset all users with an numeric ZhylonID so the process works now.

No Data should be lost!

Thanks!
