### ISSUE TITLE
Cloud Backup not automatically?

### ISSUE THREAD

**Issue by saiyajin** [Zhylon/features#5]
I've enabled the backup automatic on some of my servers. But I'm not sure if this worked since I don't see any backups in the history. 

I'm vary ängstlich davor, wo the backups my be saved and what happened if they servers are destroyed (like OVH last week).

Would love to here soon from you. 

Best regards

**Comment by TobyMaxham** [comment]
Hi,

the backup history will show after the first backup was created. 

We store our backups on multiple locations so if is not available, backups can still be accessed. 

-closed-
