### ISSUE TITLE
Sitealarm > Wrong time format

### ISSUE THREAD

**Issue by Zenonik** [Zhylon/features#6]
![grafik](https://user-images.githubusercontent.com/33786132/165903472-df1029ec-6814-4673-9cab-3dae0d9e91e4.png)
![grafik](https://user-images.githubusercontent.com/33786132/165903536-4c34020f-8a6c-494f-9802-9ce14dd59093.png)

**Comment by TobyMaxham** [comment]
The date/time format in this view is fixed now (Version 3.1).
We will do some more Translation updates in Version 3.2
