### ISSUE TITLE
Sitealarm > Mail sender

### ISSUE THREAD

**Issue by Zenonik** [Zhylon/features#9]
![grafik](https://user-images.githubusercontent.com/33786132/165932861-374aa956-9e78-4992-a13e-5c3f1301fe5b.png)
I find it a bit strange that the mails are sent as TobyMaxham and not as a Sitealarm or something like that.

**Comment by TobyMaxham** [comment]
There seems to be some general issues with mail sending. Some providers are reporting spam and DMARC compliance reports. 

I think I will switch to an beta Sitealarm account

**Comment by TobyMaxham** [comment]
Hello @Zenonik ,
we changed the Sender to beta@sitealarm.de in our Version 3.1 which was released yesterday.

For a migration to our main site we are still in a working process.
